/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import java.util.List;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author Korisnik
 */
public class UnosPredmetaForma extends javax.swing.JFrame {
    Predmet odabran;
    /**
     * Creates new form UnosPredmetaForma
     */
    public UnosPredmetaForma() {
        initComponents();
        popuniComboBox();
        jButtonOmoguciIzmenu.setVisible(false);
        jButtonSacuvajIzmenu.setVisible(false);
    }
    public UnosPredmetaForma(Predmet p) {
        initComponents();
        popuniComboBox();
        jButtonSacuvaj.setVisible(false);
        jButtonSacuvajIzmenu.setEnabled(false);
        odabran=p;
        popuniFormu(odabran);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldESBP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxKatedra = new javax.swing.JComboBox<>();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonOmoguciIzmenu = new javax.swing.JButton();
        jButtonSacuvajIzmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv");

        jLabel2.setText("ESBP");

        jLabel3.setText("Katedra");

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonOmoguciIzmenu.setText("Omoguci izmenu");
        jButtonOmoguciIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOmoguciIzmenuActionPerformed(evt);
            }
        });

        jButtonSacuvajIzmenu.setText("Sacuvaj");
        jButtonSacuvajIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajIzmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButtonSacuvaj)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOmoguciIzmenu)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldESBP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxKatedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSacuvajIzmenu)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldESBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxKatedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButtonSacuvaj)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOmoguciIzmenu)
                    .addComponent(jButtonSacuvajIzmenu))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed

        
        
        
        Predmet p = validiran();

        boolean uspesno = Controller.getInstance().ubaciPredmet(p);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Uspesno unet predmet u bazu");
            int odg=JOptionPane.showConfirmDialog(this, "Da li zelite da nastavnite sa dodavanjem?", "Potvrda", JOptionPane.YES_NO_OPTION);
            if(odg==JOptionPane.YES_OPTION){
                pripremiFormu();
            }else{
                this.dispose();
            }
        
        
        } else {
            JOptionPane.showMessageDialog(this, "Greska pri unosu predmeta u bazu");
        }


    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonOmoguciIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOmoguciIzmenuActionPerformed
        
        jTextFieldESBP.setEnabled(true);
        jTextFieldNaziv.setEnabled(true);
        jComboBoxKatedra.setEnabled(true);
        jButtonSacuvajIzmenu.setEnabled(true);
    }//GEN-LAST:event_jButtonOmoguciIzmenuActionPerformed

    private void jButtonSacuvajIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajIzmenuActionPerformed
        
        
        Predmet validiran=validiran();
        Predmet promenjen=new Predmet(odabran.getId(), validiran.getNaziv(), validiran.getEspb(), validiran.getKatedra());
        int odg=JOptionPane.showConfirmDialog(this, "Da li zelite da sacuvate izmene", "Provera", JOptionPane.YES_NO_OPTION);
        if(odg==JOptionPane.YES_OPTION){
           boolean uspesno=Controller.getInstance().izmeniPredmet(promenjen);
           if(uspesno){
               JOptionPane.showMessageDialog(this, "Promene su sacuvane u bazi");
               this.dispose();
               PrikazPredmetaForma ppf=new PrikazPredmetaForma();
               ppf.osveziTabelu();
               
           }
           else{
               JOptionPane.showMessageDialog(this, "Greska pri cuvanju promena");
           }
        }
        
        
        
    }//GEN-LAST:event_jButtonSacuvajIzmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosPredmetaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosPredmetaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosPredmetaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosPredmetaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosPredmetaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOmoguciIzmenu;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonSacuvajIzmenu;
    private javax.swing.JComboBox<Katedra> jComboBoxKatedra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldESBP;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {

        List<Katedra> lista = Controller.getInstance().vratiListuKatedri();
        lista.add(0, null);
        for (Katedra k : lista) {
            jComboBoxKatedra.addItem(k);
        }

    }

    private void pripremiFormu() {
        jTextFieldESBP.setText("");
        jTextFieldNaziv.setText("");
        jComboBoxKatedra.setSelectedItem(null);
    }

    private void popuniFormu(Predmet p) {
        
        jTextFieldNaziv.setText(p.getNaziv());
        jTextFieldESBP.setText(p.getEspb()+"");
        jComboBoxKatedra.setSelectedItem(p.getKatedra());
        
        jTextFieldNaziv.setEnabled(false);
        jTextFieldESBP.setEnabled(false);
        jComboBoxKatedra.setEnabled(false);
    
    }
    private Predmet validiran(){
        if (jTextFieldNaziv == null) {
            JOptionPane.showMessageDialog(this, "Polje naziv je prazno!");
            return null;
        }
        String naziv = jTextFieldNaziv.getText();
        if (naziv == null || naziv.isEmpty() || !naziv.matches("[a-zA-Z]+") || naziv.length() > 100) {
            JOptionPane.showMessageDialog(this, "Pogresan naziv!");
            return null;
        }

        if (jTextFieldESBP == null || jTextFieldESBP.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Polje esbp je prazno ili sadrzi slova!");
            return null;
        }

        int esbp = Integer.parseInt(jTextFieldESBP.getText());
        if(esbp<2 || esbp>10){
            JOptionPane.showMessageDialog(this, "Broj esbp nije odgovarajuci (2-10)");
            return null;
        }
        
        if(jComboBoxKatedra.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "Nije odabrana katedra!");
            return null;
        }
        
        Katedra k = (Katedra) jComboBoxKatedra.getSelectedItem();
        
        
        
        
        Predmet p = new Predmet(0, naziv, esbp, k);
        return p;
    }
}
